version: "3.9"
services:
  app:
    container_name: zalex
    image: zalex
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
